### ISSUE TITLE
CTA08 data can't be downloaded now, could you please refer this dataset, thanks a lot

### ISSUE THREAD

**Issue by zyx3216825** [BubblyYi/Coronary-Artery-Tracking-via-3D-CNN-Classification#10]

**Comment by gvieralopez** [comment]
Dear @zyx3216825

I went through the same process of gathering the dataset. It took me some month. I don't think that anybody can share it because to obtain it you have to sign a confidentiality agreement.  

To minimize your waiting, I suggest to follow this procedure:

1. Register your team at http://coronary.bigr.nl/centerlines/
2. You may get a confirmation email, but the instructions don't work (at least for me)
3. Despite if you got the email or not, fill this form http://coronary.bigr.nl/centerlines/download/dataconfidentiality.pdf 
4. Email the compiled form to Dr.Theo van Walsum (t.vanwalsum@erasmusmc.nl)

This was what resulted for me. I hope it also does for you.

**Comment by journey1234-liu** [comment]
Website http://coronary.bigr.nl/centerlines/ is not available now because we don't have permission. Is there any other way to download CAT08 dataset?
